
name: 'dbt_elt_retail'
version: '1.0.0'
config-version: 2
profile: 'dbt_elt_retail'

model-paths: ['models']
analysis-paths: ['analyses']
seed-paths: ['seeds']
macro-paths: ['macros']

models:
  dbt_elt_retail:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
